### ISSUE TITLE
"Continue Shopping" feature

### ISSUE THREAD

**Issue by chryzrose** [mathuin/pyment#71]
Create "Continue Shopping" feature from shopping cart page. There should be a "Continue Shopping" button available after selecting a jar and adding it to the user's cart. This button should return the user to the previous product screen OR it should return to the home page.

**Comment by mathuin** [comment]
I think this is pretty straightforward.  When a jar is added to the cart, I will display a continue-shopping button like you describe that will return the customer to the page where they saw the jar.

This brings up another thought on changing the product page, and I'll @-mention you when I create that issue.

**Comment by mathuin** [comment]
https://code.google.com/p/django-cart/source/browse/trunk/django-cart/templates/shop/cart.html?r=3#45 -- the views changes required for this feature

https://code.google.com/p/django-cart/source/browse/trunk/django-cart/shop/views.py?r=3#34 -- where to set the value

Tests for this will be fun.

**Comment by mathuin** [comment]
Okay, one way to write this feature is to rewrite the cart subsystem to use objects in the database instead of the session.

Adding a Cart model and having the CartItems be part of it is like Order and Picklist, but each session gets only one cart.  The items-specific bits in the system will need to be rewritten to be cart-specific, and this time perhaps there will be some additional tests.  Most of the spare routines will be parts of the class.

What other ideas are there?
